variables:
  #包名
  PACKAGE_NAME: "invoice-service.jar"
  #包路径(相对于项目根目录,以/开头)
  PACKAGE_PATH: "/target"
  #启动服务的容器数量
  CONTAINER_SCALE: "1"
  #LB开放端口号（LB数量和ip根据rancher已定死，不可配置）
  EXPORT_LB_PORT: "8001"
  #容器侧访问端口号
  CONTAINER_SERVICE_PORT: "8080"
stages:
  - deploy
  - up_lb

#dev environment
deploy_dev:
  stage: deploy
  only:
    - test
  environment:
    name: dev
  when: manual
  script:
    # package
    - mvn clean package -Dmaven.test.skip=true -Pdev
    # write docker file
    - cd /$CI_PROJECT_DIR/$PACKAGE_PATH
    - echo "FROM openjdk:8-jre" > dockerfile
    - echo "COPY $PACKAGE_NAME /opt" >> dockerfile
    - echo "RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime" >> dockerfile
    - echo "CMD [\"java\",\"-Dfile.encoding=UTF-8\",\"-Duser.timezone=Asia/Shanghai\",\"-jar\",\"/opt/$PACKAGE_NAME\"]" >> dockerfile
    # run common deploy shell
    - sh /opt/deploy-shell/deploy-common-dev.sh

up_lb_dev:
  stage: up_lb
  only:
    - test
  environment:
    name: dev
  when: manual
  script:
    - sh /opt/deploy-shell/up-lb-dev.sh

#prd environment
deploy_prd:
  stage: deploy
  only:
    - master
  environment:
    name: prd
  when: manual
  script:
    # package
    - mvn clean package -Dmaven.test.skip=true -Pprd
    # build docker image
    - cd /$CI_PROJECT_DIR/$PACKAGE_PATH
    - echo "FROM openjdk:8-jre" > dockerfile
    - echo "COPY $PACKAGE_NAME /opt" >> dockerfile
    - echo "RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime" >> dockerfile
    - echo "CMD [\"java\",\"-Dfile.encoding=UTF-8\",\"-Duser.timezone=Asia/Shanghai\",\"-jar\",\"/opt/$PACKAGE_NAME\"]" >> dockerfile
    # run common deploy shell
    - sh /opt/deploy-shell/deploy-common-prd.sh

up_lb_prd:
  stage: up_lb
  only:
    - master
  environment:
    name: prd
  when: manual
  script:
    - sh /opt/deploy-shell/up-lb-prd.sh