variables:
  #服务启动js文件名
  START_JS: "manage.js"
  #启动服务的容器数量
  CONTAINER_SCALE: "1"
  #LB开放端口号（LB数量和ip根据rancher已定死，不可配置）
  EXPORT_LB_PORT: "99"
  #容器侧访问端口号
  CONTAINER_SERVICE_PORT: "99"
stages:
  - deploy
  - up_lb

#dev environment
deploy_dev:
  stage: deploy
  only:
    - test
  environment:
    name: dev
  when: manual
  script:
    # clean and install node modules
    - rm -rf node_modules/
    - npm install
    # write docker file
    - echo "FROM node:6.9.1" > dockerfile
    - echo "WORKDIR /opt" >> dockerfile
    - echo "COPY ./ /opt" >> dockerfile
    - echo "RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime" >> dockerfile
    - echo "CMD [\"node\",\"$START_JS\"]" >> dockerfile
    # run common deploy shell
    - sh /opt/deploy-shell/deploy-common-dev.sh

up_lb_dev:
  stage: up_lb
  only:
    - test
  environment:
    name: dev
  when: manual
  script:
    - sh /opt/deploy-shell/up-lb-dev.sh


#prd environment
deploy_prd:
  stage: deploy
  only:
    - master
  environment:
    name: prd
  when: manual
  script:
    # clean and install node modules
    - rm -rf node_modules/
    - npm install
    # write docker file
    - echo "FROM node:6.9.1" > dockerfile
    - echo "WORKDIR /opt" >> dockerfile
    - echo "COPY ./ /opt" >> dockerfile
    - echo "RUN cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime" >> dockerfile
    - echo "CMD [\"node\",\"$START_JS\"]" >> dockerfile
    # run common deploy shell
    - sh /opt/deploy-shell/deploy-common-prd.sh

up_lb_prd:
  stage: up_lb
  only:
    - master
  environment:
    name: prd
  when: manual
  script:
    - sh /opt/deploy-shell/up-lb-prd.sh